language: generic
sudo: required
notifications:
  email: false
services:
  - docker
install:
  - docker pull maximbaz/arch-build-aur
script:
  # Remove /usr/sbin to fix "ImportError: cannot import name 'codegen_main'"
  - export PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/sbin:/bin:/snap/bin
  - docker run --rm -v $(pwd):/pkg maximbaz/arch-build-aur /bin/bash -c '/build-aur webkitgtk'
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  skip_cleanup: true
  file_glob: true
  file: ./*
  on:
    tags: true
